# Generated by Django 2.0.13 on 2019-08-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20190714_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='documentos.Categoria_doc'),
        ),
        migrations.AlterField(
            model_name='relacion',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='documentos.Categoria_doc'),
        ),
        migrations.AlterField(
            model_name='relacion',
            name='pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertenece', to='documentos.Categoria_doc'),
        ),
    ]
