# Generated by Django 2.0.13 on 2019-08-22 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_auto_20190819_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo_pdf',
            field=models.FileField(default=None, upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc'])]),
        ),
    ]
