# Generated by Django 2.0.13 on 2019-08-22 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_auto_20190822_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo_pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
