# Generated by Django 2.0.13 on 2019-08-22 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_auto_20190822_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='archivo_pdf',
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
