# Generated by Django 2.0.13 on 2019-09-07 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0006_auto_20190822_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='calibrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='calibrador_modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Roche', 'Roche'), ('Abbot', 'Abbot'), ('Ran', 'Randox')], max_length=5)),
                ('nombre', models.CharField(choices=[('4738551190', 'Calibrador TSH, para 801, Roche'), ('4738551190', 'Calibrador FT3, para 801, Roche')], max_length=10)),
                ('descripcion', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(choices=[('M', 'Medición'), ('A', 'Analítico'), ('O', 'Otro')], max_length=1)),
                ('codigo', models.CharField(default='Genérico', help_text='Poner el código de el instrumento si es referido en el documento, para que sea fácil encontrarlo', max_length=200)),
                ('descripcion', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_prep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relacion_doc_puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion_instr_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rol_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Puesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='categoria_doc',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Sector'),
        ),
        migrations.AddField(
            model_name='relacion_instr_doc',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Categoria_doc'),
        ),
        migrations.AddField(
            model_name='relacion_instr_doc',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Instrumento'),
        ),
        migrations.AddField(
            model_name='relacion_doc_puesto',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Categoria_doc'),
        ),
        migrations.AddField(
            model_name='relacion_doc_puesto',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Puesto'),
        ),
        migrations.AddField(
            model_name='registro_prep',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Categoria_doc'),
        ),
        migrations.AddField(
            model_name='registro_prep',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.calibrador'),
        ),
        migrations.AddField(
            model_name='calibrador',
            name='calibrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.calibrador_modelo'),
        ),
    ]
