# Generated by Django 2.0.13 on 2019-09-22 17:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0007_auto_20190907_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parte_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(help_text='Título de esta parte')),
                ('tipo', models.CharField(choices=[('I', 'Imágen'), ('T', 'Texto')], max_length=5)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'gif'])])),
                ('posicion_en_doc', models.IntegerField(help_text='posicion que tiene este campo en el documento')),
                ('texto', models.TextField(help_text='Insertar el texto del documento')),
                ('editable', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Categoria_doc')),
            ],
        ),
        migrations.RenameModel(
            old_name='Relacion',
            new_name='Relacion_docs',
        ),
        migrations.RemoveField(
            model_name='calibrador',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='calibrador',
            name='calibrador',
        ),
        migrations.RemoveField(
            model_name='calibrador_modelo',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='registro_prep',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='registro_prep',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='registro_prep',
            name='material',
        ),
        migrations.RemoveField(
            model_name='relacion_doc_puesto',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='relacion_doc_puesto',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='relacion_instr_doc',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='relacion_instr_doc',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='rol_usuario',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='rol_usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='documento',
            name='editable',
            field=models.BooleanField(default=True, help_text='Indica si el documento se puede editar, si está o estuvo publicado, no se  puede'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='relacion_docs',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='documentos.Documento'),
        ),
        migrations.DeleteModel(
            name='calibrador',
        ),
        migrations.DeleteModel(
            name='calibrador_modelo',
        ),
        migrations.DeleteModel(
            name='Instrumento',
        ),
        migrations.DeleteModel(
            name='Puesto',
        ),
        migrations.DeleteModel(
            name='Registro_prep',
        ),
        migrations.DeleteModel(
            name='Relacion_doc_puesto',
        ),
        migrations.DeleteModel(
            name='Relacion_instr_doc',
        ),
        migrations.DeleteModel(
            name='Rol_usuario',
        ),
    ]
