# Generated by Django 2.0.13 on 2019-09-22 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_auto_20190922_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='pertenece_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pertenece_a', to='documentos.Categoria_doc'),
        ),
        migrations.AlterField(
            model_name='relacion_docs',
            name='pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertenece', to='documentos.Documento'),
        ),
    ]
