# Generated by Django 2.0.13 on 2019-09-28 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0010_auto_20190922_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateField(help_text='fecha en que se hizo la Revision')),
                ('comentario_revision', models.CharField(max_length=500)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Documento')),
            ],
        ),
        migrations.AlterField(
            model_name='parte_doc',
            name='tipo',
            field=models.CharField(choices=[('I', 'Imágen'), ('T', 'Texto')], max_length=1),
        ),
    ]
