# Generated by Django 2.0.13 on 2019-10-02 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0011_auto_20190927_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relacion_docs',
            name='pertenece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pertenece', to='documentos.Documento'),
        ),
    ]
