# Generated by Django 2.0.13 on 2019-07-14 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0002_auto_20190714_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionCorrectiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(help_text='Describir cómo se piensa corregir la acción que genera la NC,')),
                ('publicado', models.BooleanField(default=False, help_text='Indica si la entrada está aceptada.')),
                ('fechalimite', models.DateTimeField(help_text='Ingresar la fecha en la cual debe estar implementada la AC \n con el siguiente formato: dd/mm/aaaa hh:mm:ss')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccionInm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(help_text='Describir cómo se trato corregir la acción que genera la NC, en una prímera instancia')),
                ('publicado', models.BooleanField(default=False, help_text='Indica si la entrada está aceptada.')),
                ('fecha_publicado', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisCausa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descr', models.TextField(help_text='Acá se describe el análisis de causa de la  NC')),
                ('publicado', models.BooleanField(default=False, help_text='Indica si la entrada está aceptada.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.FileField(upload_to='archivos/')),
                ('descr', models.TextField(help_text='Describir el archivo que se sube.')),
                ('publicado', models.BooleanField(default=False, help_text='Indica si la entrada está aceptada.')),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CierreNC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(help_text='Informar sobre algo especial en el cierre de NC')),
                ('aceptado', models.BooleanField(default=False, help_text='Indica si el cierre de nc está aceptado.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuyente', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_suceso', models.DateTimeField(help_text='Ingresar dd/mm/aaaa hh:mm:ss')),
                ('cerrada', models.BooleanField(default=False, help_text='Indica si la NC está cerrada.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='documentos.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='VerificaAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicado', models.BooleanField(default=False, help_text='Indica si la entrada está aceptada.')),
                ('fechaVerif', models.DateTimeField()),
                ('resultado', models.TextField()),
                ('metodoVerif', models.TextField()),
                ('ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_nc.AccionCorrectiva')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_nc.NC')),
            ],
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_nc.NC'),
        ),
        migrations.AddField(
            model_name='cierrenc',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_nc.NC'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='nc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_nc.NC'),
        ),
        migrations.AddField(
            model_name='analisiscausa',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_nc.NC'),
        ),
        migrations.AddField(
            model_name='accioninm',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_nc.NC'),
        ),
        migrations.AddField(
            model_name='accioncorrectiva',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_nc.NC'),
        ),
    ]
