# Generated by Django 2.0.13 on 2019-07-15 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_nc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accioncorrectiva',
            old_name='text',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='accioncorrectiva',
            old_name='fechalimite',
            new_name='fecha_limite',
        ),
        migrations.RenameField(
            model_name='accioninm',
            old_name='text',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='analisiscausa',
            old_name='descr',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='archivo',
            old_name='document',
            new_name='archivo',
        ),
        migrations.RenameField(
            model_name='archivo',
            old_name='descr',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='verificaac',
            old_name='fechaVerif',
            new_name='fecha_verificacion',
        ),
        migrations.RenameField(
            model_name='verificaac',
            old_name='metodoVerif',
            new_name='metodo_verificacion',
        ),
        migrations.AddField(
            model_name='verificaac',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verificaac',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to=settings.AUTH_USER_MODEL),
        ),
    ]
